name: Build Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Image "${{ matrix.image }}"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ matrix.image }}/

    matrix: 
      image: 
        - php7.4-cli
        - php7.4-fpm
        - php7.4-fpm-rendering
        - php8.0-cli
        - php8.0-fpm
    
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: micky5991/docker-php-base:latest-${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

