name: Build Docker Images

on:
  push:
    branches:
      - master
      - add-actions
  pull_request:
    branches:
      - master
      - add-actions

jobs:
  variables:
    runs-on: ubuntu-latest
    name: Create variables

    outputs:
      istag: ${{ steps.vars.outputs.is_tag }}
      ref: ${{ steps.vars.outputs.ref }}
      version: ${{ steps.vars.outputs.version }}
      shashort: ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0

      - id: vars
        name: Set variables
        run: |
          echo ::set-output name=ref::${GITHUB_REF#refs/*/}
          echo ::set-output name=is_tag::${{ startsWith(github.ref, 'refs/tags/') }}
          echo ::set-output name=version::${{ steps.previoustag.outputs.tag }}
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

  build:
    name: Build Image "${{ matrix.image }}"
    runs-on: ubuntu-latest
    needs: [ variables ]

    strategy:
      matrix: 
        image: 
          - php7.4-cli
          - php7.4-fpm
          - php7.4-fpm-rendering
          - php8.0-cli
          - php8.0-fpm
    
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}
          push: false
          tags: micky5991/docker-php-base:latest-${{ matrix.image }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockerimage-${{ matrix.image }}
          path: /tmp/image.tar

  push:
    needs: [ variables, build ]
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        image: 
          - php7.4-cli
          - php7.4-fpm
          - php7.4-fpm-rendering
          - php8.0-cli
          - php8.0-fpm
    
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dockerimage-${{ matrix.image }}
          path: /tmp

      - name: Load docker image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a

      - name: Retag docker image
        run: |
          docker tag micky5991/docker-php-base:latest-${{ matrix.image }} micky5991/docker-php-base:${{ needs.variables.outputs.ref }}-${{ matrix.image }}
          docker image ls -a

      - name: Push docker image
        run: |
          docker push micky5991/docker-php-base:${{ needs.variables.outputs.ref }}-${{ matrix.image }}

